set MATLAB=C:\Program Files\MATLAB\R2016b
"%MATLAB%\bin\%MATLAB_WIN_VER%\gmake" -f etc.mk  GENERATE_ASAP2=0 DOWNLOADAPPLICATION=1 STM32CUBEMXPATHUPDATE=1 STM32CUBEMXPATH="C:\Program Files\STMicroelectronics\STM32Cube\STM32CubeMX" TARGET_INST_FULLPATH="D:\Users\Kevin\Documents\MATLAB\STM32-MAT\STM32" IOC_FULLPATH=".\etc.ioc" IT_HANDLER_OPTIM=1 ISPROTECTINGMODEL=NOTPROTECTING
