set MATLAB=C:\Program Files\MATLAB\R2016a
"%MATLAB%\bin\%MATLAB_WIN_VER%\gmake" -f etc_discovery.mk  GENERATE_ASAP2=0 DOWNLOADAPPLICATION=1 STM32CUBEMXPATHUPDATE=1 STM32CUBEMXPATH="C:\Program Files\STMicroelectronics\STM32Cube\STM32CubeMX" TARGET_INST_FULLPATH="D:\stm32-throttle-controller\tools\STM32" IOC_FULLPATH=".\etc_discovery.ioc" IT_HANDLER_OPTIM=1 ISPROTECTINGMODEL=NOTPROTECTING
